version: "3"
   
services:
  db:
    image: postgres:15.2
    container_name: db
    hostname: db
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5532:5432"
    env_file:
      - .env